# =============================================
# PLANLY APP - DOCKER COMPOSE PRODUCTION
# VPS: 103.56.148.34:8082
# Untuk deployment via Portainer Git Repository
# =============================================
# Compose path di Portainer: compose.production.yaml
# Repository reference: refs/heads/main
# =============================================

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.production
        container_name: planly-app
        restart: unless-stopped
        ports:
            - "8082:80"
        environment:
            SERVER_NAME: ":80"
            FRANKENPHP_CONFIG: "root public/"
            APP_NAME: "Planly App"
            APP_ENV: production
            APP_DEBUG: "false"
            APP_TIMEZONE: Asia/Jakarta
            APP_URL: "http://103.56.148.34:8082"
            APP_KEY: "${APP_KEY:-}"
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: "3306"
            DB_DATABASE: planly_production
            DB_USERNAME: planly_user
            DB_PASSWORD: "${DB_PASSWORD:-PlanlySecure2026!}"
            FILESYSTEM_DISK: public
            SESSION_DRIVER: database
            CACHE_STORE: database
            QUEUE_CONNECTION: database
        volumes:
            - app-storage:/app/storage/app
            - app-logs:/app/storage/logs
        networks:
            - planly-network
        depends_on:
            mysql:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/up" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

    mysql:
        image: mysql:8.4
        container_name: planly-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-PlanlyRoot2026!}"
            MYSQL_DATABASE: planly_production
            MYSQL_USER: planly_user
            MYSQL_PASSWORD: "${DB_PASSWORD:-PlanlySecure2026!}"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - planly-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-PlanlyRoot2026!}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-authentication-plugin=mysql_native_password

networks:
    planly-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
    app-storage:
        driver: local
    app-logs:
        driver: local
